"""
Django settings for SBug project.

Generated by 'django-admins startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
# import django_redis
import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s@(*t7ft*e!ve&6ecf$z_*&j)q$iv!x)*-66khg(hbbcxcms2d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web',
    'app01',
    'captcha',
    'mdeditor'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'web.middlewares.auth.AuthMIddleware'
]

ROOT_URLCONF = 'SBug.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'web/templates',
            BASE_DIR / 'app01/templates'
                 ]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SBug.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

#时区
# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

#根据timez设置时间
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, "app01", "static"),
    # os.path.join(BASE_DIR, "web", "static"),
    os.path.join(BASE_DIR, "static"),
]



# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TENCENT_SMS_APP_ID="app_Id"
TENCENT_SMS_APP_KEY ="app_key"
TENCENT_SMS_SIGN="签名内容"

TENCENT_SMS_TYPE={
    'login':'2055395',
    'register':'2055394',
    'update_password':'2055398'
}

#未登陆，禁止访问
BLACK_REGEX_URL_LIST=[
    '/project',
    '/manage',
    '/invite/join'
    '/pay',
    '/payment'


]


# 1. 设置用户属性, 包括 secret_id, secret_key, region等。Appid 已在 CosConfig 中移除，请在参数 Bucket 中带上 Appid。Bucket 由 BucketName-Appid 组成
  # 用户的 SecretId，建议使用子账号密钥，授权遵循最小权限指引，降低使用风险。子账号密钥获取可参见 https://cloud.tencent.com/document/product/598/37140
COS_SECRET_ID=''
# 用户的 SecretKey，建议使用子账号密钥，授权遵循最小权限指引，降低使用风险。子账号密钥获取可参见 https://cloud.tencent.com/document/product/598/37140
COS_SECRET_KEY=''
COS_REGION= 'ap-chengdu'




X_FRAME_OPTIONS = 'SAMEORIGIN'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')
MEDIA_URL = '/media/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "app01", "media"),
    os.path.join(BASE_DIR, "web", "media"),
]


MDEDITOR_CONFIGS = {
    'default':{
        # 'width': '90% ',  # Custom edit box width
    # 'height': 500,  # Custom edit box height
    'toolbar': ["undo", "redo", "|",
    "bold", "del", "italic", "quote", "ucwords", "uppercase", "lowercase", "|",
    "h1", "h2", "h3", "h5", "h6", "|",
    "list-ul", "list-ol", "hr", "|",
    "link", "reference-link", "image", "code", "preformatted-text", "code-block", "table", "datetime",
    "emoji", "html-entities", "pagebreak", "goto-line", "|",
    "help", "info",
    "||", "preview", "watch", "fullscreen"],  # custom edit box toolbar 
    'upload_image_formats': ["jpg", "jpeg", "gif", "png", "bmp", "webp"],  # image upload format type
    'image_folder': 'mdeditor',  # image save the folder name,
    # 'imageUploadURL'
    'theme': 'default',  # edit box theme, dark / default
    'preview_theme': 'default',  # Preview area theme, dark / default
    'editor_theme': 'default',  # edit area theme, pastel-on-dark / default
    'toolbar_autofixed': True,  # Whether the toolbar capitals
    'search_replace': True,  # Whether to open the search for replacement
    'emoji': True,  # whether to open the expression function
    'tex': True,  # whether to open the tex chart function
    'flow_chart': True,  # whether to open the flow chart function
    'sequence': True, # Whether to open the sequence diagram function
        'watch': True,  # Live preview
        'lineWrapping': False,  # lineWrapping
        'lineNumbers': False,  # lineNumbers
        'language': 'zh'  # zh / en / es 
    }

}



try:
    from .local_settings import *
except ImportError:
    pass
